Repository SLIIT-PROJECT-THIRD/Research-Project-Management-Tool-Backend, pull requests merged in 2022-05, with the labels that each got.

#2 student APIs udated for create and Update
  README.md
  controller/Student.js
  models/Student.js
Labels: enhancement

#4 Implemented the backend of Admin
  models/uprofile.js
  package-lock.json
  package.json
  routes/uprofile.js
  server.js
Labels: enhancement

#6 Changes to Backend Admin
  models/uprofile.js
Labels: fix

#7 default route message changed
  server.js
Labels: enhancement

#8 Implemented the staff backend
  models/staff.js
  routes/staff.js
  server.js
Labels: enhancement

#9 server updated
  server.js
Labels: bug, fix

#10 updated
  controller/Student.js
  package-lock.json
Labels: bug, fix

#12 Student Registration and Login Backend implemnted
  controller/Student.js
  models/Student.js
  routes/Student.js
Labels: enhancement, fix
